name: Job Search Assistant

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"

jobs:
  search-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Job Search Assistant
        run: python jobs.py
